In [1]:
from transfermarkt import Player

In [2]:
playerId = 28003

messi = Player(playerId)

C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py:73: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 73 of the file C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  img = BeautifulSoup(row['team']).find('img')
C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py:75: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 75 of the file C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  img = BeautifulSoup(row['opponent']).find('img')

In [3]:
messi.matches()

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
0,LaLiga,7,2004-10-16,A,FC Barcelona,RCD Espanyol Barcelona,0:1,RW,0,0,NaN,NaN,NaN,8
1,LaLiga,8,2004-10-24,H,FC Barcelona,CA Osasuna,3:0,LW,0,0,NaN,NaN,NaN,19
466,Copa del Rey,Second Round,2004-10-27,A,FC Barcelona,UDA Gramenet,1:0 AET,RW,0,0,NaN,NaN,NaN,73
2,LaLiga,14,2004-12-04,H,FC Barcelona,Málaga CF,4:0,RW,0,0,NaN,NaN,NaN,9
557,UEFA Champions League,Group F,2004-12-07,A,FC Barcelona,Shakhtar Donetsk,2:0,CF,0,0,NaN,NaN,NaN,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,LaLiga,16,2019-12-07,H,FC Barcelona,RCD Mallorca,5:2,RW,3,0,NaN,NaN,NaN,90
462,LaLiga,17,2019-12-14,A,FC Barcelona,Real Sociedad,2:2,RW,0,1,NaN,NaN,NaN,90
463,LaLiga,10,2019-12-18,H,FC Barcelona,Real Madrid,0:0,RW,0,0,NaN,NaN,NaN,90
464,LaLiga,18,2019-12-21,H,FC Barcelona,Deportivo Alavés,4:1,RW,1,0,NaN,NaN,NaN,90
465,LaLiga,19,2020-01-04,A,FC Barcelona,RCD Espanyol Barcelona,2:2,RW,0,0,NaN,NaN,NaN,90

In [4]:
messi.performance(by='competition') # Messi stats by competition

                       appearances  goals  assists  minutesPlayed
competition
Copa del Rey                    73     51       34           5821
FIFA Club World Cup              5      5        1            427
LaLiga                         466    432      175          37416
Supercopa                       18     13        5           1464
UEFA Champions League          140    114       35          11522
UEFA Super Cup                   4      3        2            420

In [5]:
messi.performance(by='position') # Messi stats by position

          appearances  goals  assists  minutesPlayed
position
AM                  7     10        3            603
CF                246    263       99          20333
LW                  7      1        5            417
RW                405    308      128          32181
SS                 41     36       17           3536

In [9]:
messi.matches(competition='LaLiga') # Messi all in LaLiga

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
0,LaLiga,7,2004-10-16,A,FC Barcelona,RCD Espanyol Barcelona,0:1,RW,0,0,NaN,NaN,NaN,8
1,LaLiga,8,2004-10-24,H,FC Barcelona,CA Osasuna,3:0,LW,0,0,NaN,NaN,NaN,19
2,LaLiga,14,2004-12-04,H,FC Barcelona,Málaga CF,4:0,RW,0,0,NaN,NaN,NaN,9
3,LaLiga,15,2004-12-11,A,FC Barcelona,Albacete Balompié,1:2,LW,0,0,NaN,NaN,NaN,1
4,LaLiga,17,2004-12-21,H,FC Barcelona,Levante UD,2:1,RW,0,0,NaN,NaN,NaN,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,LaLiga,16,2019-12-07,H,FC Barcelona,RCD Mallorca,5:2,RW,3,0,NaN,NaN,NaN,90
462,LaLiga,17,2019-12-14,A,FC Barcelona,Real Sociedad,2:2,RW,0,1,NaN,NaN,NaN,90
463,LaLiga,10,2019-12-18,H,FC Barcelona,Real Madrid,0:0,RW,0,0,NaN,NaN,NaN,90
464,LaLiga,18,2019-12-21,H,FC Barcelona,Deportivo Alavés,4:1,RW,1,0,NaN,NaN,NaN,90
465,LaLiga,19,2020-01-04,A,FC Barcelona,RCD Espanyol Barcelona,2:2,RW,0,0,NaN,NaN,NaN,90

In [10]:
messi.matches(opponent='Real Madrid') # Messi all matches against Real Madrid

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
11,LaLiga,12,2005-11-19,A,FC Barcelona,Real Madrid,0:3,RW,0,1,NaN,NaN,NaN,70
30,LaLiga,7,2006-10-22,A,FC Barcelona,Real Madrid,2:0,RW,0,0,NaN,NaN,NaN,90
37,LaLiga,26,2007-03-10,H,FC Barcelona,Real Madrid,3:3,RW,3,0,NaN,NaN,NaN,90
75,LaLiga,36,2008-05-07,A,FC Barcelona,Real Madrid,4:1,RW,0,1,NaN,NaN,NaN,90
90,LaLiga,15,2008-12-13,H,FC Barcelona,Real Madrid,2:0,RW,1,0,89',NaN,NaN,90
107,LaLiga,34,2009-05-02,A,FC Barcelona,Real Madrid,2:6,RW,2,1,NaN,NaN,NaN,90
119,LaLiga,12,2009-11-29,H,FC Barcelona,Real Madrid,1:0,RW,0,0,NaN,NaN,NaN,90
136,LaLiga,31,2010-04-10,A,FC Barcelona,Real Madrid,0:2,CF,1,0,19',NaN,NaN,90
154,LaLiga,13,2010-11-29,H,FC Barcelona,Real Madrid,5:0,CF,0,2,44',NaN,NaN,90
172,LaLiga,32,2011-04-16,A,FC Barcelona,Real Madrid,1:1,CF,1,0,NaN,NaN,NaN,90
491,Copa del Rey,Final,2011-04-20,H,FC Barcelona,Real Madrid,0:1 AET,CF,0,0,63',NaN,NaN,120
611,UEFA Champions League,Semi-Finals 1st Leg,2011-04-27,A,FC Barcelona,Real Madrid,0:2,CF,2,0,NaN,NaN,NaN,90
612,UEFA Champions League,Semi-Finals 2nd Leg,2011-05-03,H,FC Barcelona,Real Madrid,1:1,RW,0,0,NaN,NaN,NaN,90
544,Supercopa,final 1st leg,2011-08-14,A,FC Barcelona,Real Madrid,2:2,CF,1,1,NaN,NaN,NaN,90
545,Supercopa,final 2nd leg,2011-08-17,H,FC Barcelona,Real Madrid,3:2,CF,2,1,NaN,NaN,NaN,90
192,LaLiga,16,2011-12-10,A,FC Barcelona,Real Madrid,1:3,RW,0,1,36',NaN,NaN,90
494,Copa del Rey,Quarter-Finals 1st leg,2012-01-18,A,FC Barcelona,Real Madrid,1:2,CF,0,1,NaN,NaN,NaN,90
495,Copa del Rey,Quarter-Finals 2nd leg,2012-01-25,H,FC Barcelona,Real Madrid,2:2,RW,0,1,45',NaN,NaN,90
209,LaLiga,35,2012-04-21,H,FC Barcelona,Real Madrid,1:2,CF,0,0,NaN,NaN,NaN,90
546,Supercopa,final 1st leg,2012-08-23,H,FC Barcelona,Real Madrid,3:2,CF,1,0,NaN,NaN,NaN,90
547,Supercopa,final 2nd leg,2012-08-29,A,FC Barcelona,Real Madrid,2:1,CF,1,0,NaN,NaN,NaN,90
220,LaLiga,7,2012-10-07,H,FC Barcelona,Real Madrid,2:2,CF,2,0,NaN,NaN,NaN,90
502,Copa del Rey,Semi-Finals 1st Leg,2013-01-30,A,FC Barcelona,Real Madrid,1:1,CF,0,1,NaN,NaN,NaN,90
503,Copa del Rey,Semi-Finals 2nd Leg,2013-02-26,H,FC Barcelona,Real Madrid,1:3,CF,0,0,NaN,NaN,NaN,90
239,LaLiga,26,2013-03-02,A,FC Barcelona,Real Madrid,2:1,CF,1,0,NaN,NaN,NaN,90
253,LaLiga,10,2013-10-26,H,FC Barcelona,Real Madrid,2:1,RW,0,0,NaN,NaN,NaN,90
267,LaLiga,29,2014-03-23,A,FC Barcelona,Real Madrid,3:4,CF,3,1,NaN,NaN,NaN,90
509,Copa del Rey,Final,2014-04-16,H,FC Barcelona,Real Madrid,1:2,CF,0,0,NaN,NaN,NaN,90
285,LaLiga,9,2014-10-25,A,FC Barcelona,Real Madrid,3:1,CF,0,0,9',NaN,NaN,90
304,LaLiga,28,2015-03-22,H,FC Barcelona,Real Madrid,2:1,RW,0,1,NaN,NaN,NaN,90
321,LaLiga,12,2015-11-21,A,FC Barcelona,Real Madrid,0:4,RW,0,0,NaN,NaN,NaN,34
340,LaLiga,31,2016-04-02,H,FC Barcelona,Real Madrid,1:2,RW,0,0,NaN,NaN,NaN,90
358,LaLiga,14,2016-12-03,H,FC Barcelona,Real Madrid,1:1,RW,0,0,NaN,NaN,NaN,90
376,LaLiga,33,2017-04-23,A,FC Barcelona,Real Madrid,2:3,RW,2,0,90',NaN,NaN,90
554,Supercopa,final 1st leg,2017-08-13,H,FC Barcelona,Real Madrid,1:3,RW,1,0,40',NaN,NaN,90
555,Supercopa,final 2nd leg,2017-08-16,A,FC Barcelona,Real Madrid,2:0,SS,0,0,NaN,NaN,NaN,90
398,LaLiga,17,2017-12-23,A,FC Barcelona,Real Madrid,0:3,SS,1,1,NaN,NaN,NaN,90
415,LaLiga,36,2018-05-06,H,FC Barcelona,Real Madrid,2:2,SS,1,0,45',NaN,NaN,90
536,Copa del Rey,Semi-Finals 1st Leg,2019-02-06,H,FC Barcelona,Real Madrid,1:1,RW,0,0,NaN,NaN,NaN,27
537,Copa del Rey,Semi-Finals 2nd Leg,2019-02-27,A,FC Barcelona,Real Madrid,0:3,SS,0,0,NaN,NaN,NaN,90
441,LaLiga,26,2019-03-02,A,FC Barcelona,Real Madrid,0:1,RW,0,0,NaN,NaN,NaN,90
463,LaLiga,10,2019-12-18,H,FC Barcelona,Real Madrid,0:0,RW,0,0,NaN,NaN,NaN,90

In [11]:
messi.matches(opponent='Real Madrid', competition='UEFA Champions League') # Messi all matches against Real Madrid in UEFA Champions League

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
611,UEFA Champions League,Semi-Finals 1st Leg,2011-04-27,A,FC Barcelona,Real Madrid,0:2,CF,2,0,NaN,NaN,NaN,90
612,UEFA Champions League,Semi-Finals 2nd Leg,2011-05-03,H,FC Barcelona,Real Madrid,1:1,RW,0,0,NaN,NaN,NaN,90

In [6]:
messi.matches()['goals'].sum() # Messi all-time goals

618

In [7]:
messi.matches()['assists'].sum() # Messi all-time goals

252