In [1]:
from transfermarkt import Player

In [2]:
playerId = 28003

messi = Player(playerId)

C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py:73: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 73 of the file C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  img = BeautifulSoup(row['team']).find('img')
C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py:75: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 75 of the file C:\Users\Wilson Felipe\Documents\GitHub\simple-transfermarkt-crawler\transfermarkt.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  img = BeautifulSoup(row['opponent']).find('img')

In [11]:
messi.matches(competition='')

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
0,LaLiga,7,2004-10-16,A,FC Barcelona,RCD Espanyol Barcelona,0:1,RW,0,0,NaN,NaN,NaN,8
1,LaLiga,8,2004-10-24,H,FC Barcelona,CA Osasuna,3:0,LW,0,0,NaN,NaN,NaN,19
466,Copa del Rey,Second Round,2004-10-27,A,FC Barcelona,UDA Gramenet,1:0 AET,RW,0,0,NaN,NaN,NaN,73
2,LaLiga,14,2004-12-04,H,FC Barcelona,Málaga CF,4:0,RW,0,0,NaN,NaN,NaN,9
557,UEFA Champions League,Group F,2004-12-07,A,FC Barcelona,Shakhtar Donetsk,2:0,CF,0,0,NaN,NaN,NaN,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,LaLiga,16,2019-12-07,H,FC Barcelona,RCD Mallorca,5:2,RW,3,0,NaN,NaN,NaN,90
462,LaLiga,17,2019-12-14,A,FC Barcelona,Real Sociedad,2:2,RW,0,1,NaN,NaN,NaN,90
463,LaLiga,10,2019-12-18,H,FC Barcelona,Real Madrid,0:0,RW,0,0,NaN,NaN,NaN,90
464,LaLiga,18,2019-12-21,H,FC Barcelona,Deportivo Alavés,4:1,RW,1,0,NaN,NaN,NaN,90
465,LaLiga,19,2020-01-04,A,FC Barcelona,RCD Espanyol Barcelona,2:2,RW,0,0,NaN,NaN,NaN,90

In [12]:
messi.performance(by='competition') # Messi stats by competition

                       appearances  goals  assists  minutesPlayed
competition
Copa del Rey                    73     51       34           5821
FIFA Club World Cup              5      5        1            427
LaLiga                         466    432      175          37416
Supercopa                       18     13        5           1464
UEFA Champions League          140    114       35          11522
UEFA Super Cup                   4      3        2            420

In [13]:
messi.performance(by='position') # Messi stats by position

          appearances  goals  assists  minutesPlayed
position
AM                  7     10        3            603
CF                246    263       99          20333
LW                  7      1        5            417
RW                405    308      128          32181
SS                 41     36       17           3536

In [18]:
messi.matches()['goals'].sum() # Messi all-time goals

618

In [20]:
messi.matches()['assists'].sum() # Messi all-time goals

252

In [79]:
competition = 'LaLiga'
opponent=''
year='2012'

In [80]:
messi.df.loc[(messi.df['competition'].str.contains('^'+competition, na=False)) & (messi.df['opponent'].str.contains('^'+opponent, na=False))]

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
0,LaLiga,7,2004-10-16,A,FC Barcelona,RCD Espanyol Barcelona,0:1,RW,0,0,NaN,NaN,NaN,8
1,LaLiga,8,2004-10-24,H,FC Barcelona,CA Osasuna,3:0,LW,0,0,NaN,NaN,NaN,19
2,LaLiga,14,2004-12-04,H,FC Barcelona,Málaga CF,4:0,RW,0,0,NaN,NaN,NaN,9
3,LaLiga,15,2004-12-11,A,FC Barcelona,Albacete Balompié,1:2,LW,0,0,NaN,NaN,NaN,1
4,LaLiga,17,2004-12-21,H,FC Barcelona,Levante UD,2:1,RW,0,0,NaN,NaN,NaN,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,LaLiga,16,2019-12-07,H,FC Barcelona,RCD Mallorca,5:2,RW,3,0,NaN,NaN,NaN,90
462,LaLiga,17,2019-12-14,A,FC Barcelona,Real Sociedad,2:2,RW,0,1,NaN,NaN,NaN,90
463,LaLiga,10,2019-12-18,H,FC Barcelona,Real Madrid,0:0,RW,0,0,NaN,NaN,NaN,90
464,LaLiga,18,2019-12-21,H,FC Barcelona,Deportivo Alavés,4:1,RW,1,0,NaN,NaN,NaN,90
465,LaLiga,19,2020-01-04,A,FC Barcelona,RCD Espanyol Barcelona,2:2,RW,0,0,NaN,NaN,NaN,90

In [85]:
messi.df['date'].dt.year == 2004

0       True
1       True
466     True
2       True
557     True
       ...
461    False
462    False
463    False
464    False
465    False
Name: date, Length: 706, dtype: bool

In [55]:
messi.df

,competition,matchday,date,venue,team,opponent,result,position,goals,assists,yellow,secondYellow,red,minutesPlayed
0,LaLiga,7,2004-10-16,A,FC Barcelona,RCD Espanyol Barcelona,0:1,RW,0,0,NaN,NaN,NaN,8
1,LaLiga,8,2004-10-24,H,FC Barcelona,CA Osasuna,3:0,LW,0,0,NaN,NaN,NaN,19
466,Copa del Rey,Second Round,2004-10-27,A,FC Barcelona,UDA Gramenet,1:0 AET,RW,0,0,NaN,NaN,NaN,73
2,LaLiga,14,2004-12-04,H,FC Barcelona,Málaga CF,4:0,RW,0,0,NaN,NaN,NaN,9
557,UEFA Champions League,Group F,2004-12-07,A,FC Barcelona,Shakhtar Donetsk,2:0,CF,0,0,NaN,NaN,NaN,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,LaLiga,16,2019-12-07,H,FC Barcelona,RCD Mallorca,5:2,RW,3,0,NaN,NaN,NaN,90
462,LaLiga,17,2019-12-14,A,FC Barcelona,Real Sociedad,2:2,RW,0,1,NaN,NaN,NaN,90
463,LaLiga,10,2019-12-18,H,FC Barcelona,Real Madrid,0:0,RW,0,0,NaN,NaN,NaN,90
464,LaLiga,18,2019-12-21,H,FC Barcelona,Deportivo Alavés,4:1,RW,1,0,NaN,NaN,NaN,90
465,LaLiga,19,2020-01-04,A,FC Barcelona,RCD Espanyol Barcelona,2:2,RW,0,0,NaN,NaN,NaN,90